### ISSUE TITLE
No animation option

### ISSUE THREAD

**Issue by GhitaB** [mintchaos/flippant.js#24]
Is there any option to avoid the animation effect?

My code is:

``` js
flippant.flip(front, back_content, 'modal');
```

**Comment by sne11ius** [comment]
Hey,
Actually, flippantjs is quite lightweight. If you don't want any animation
at all, I doubt you need it. Just add buttons to hide one element and
remove the other ;)
If you still want flippantjs without animations, you can just remove most
of the CSS.
Finally: Afaik there is no such option and I don't think it would make
sense.

Am Freitag, 4. Juli 2014 schrieb Ghita Bizau :

**Comment by GhitaB** [comment]
Ok. Thank you.
But what part of CSS should be removed?

**Comment by sne11ius** [comment]
Sorry, I can't tell you without having a look at it. And right now, I have
to watch the match Germany vs France ;)

Am Freitag, 4. Juli 2014 schrieb Ghita Bizau :

**Comment by GhitaB** [comment]
No problem. :D

**Comment by GhitaB** [comment]
Solved: https://github.com/GhitaB/overlay.js
