### ISSUE TITLE
IE10 Issues

### ISSUE THREAD

**Issue by EricLayne** [mintchaos/flippant.js#5]
Very cool library!  Doesn't look quite right and the update button doesn't work in IE10.

**Comment by ghost** [comment]
I noticed that too, it only seems to be the online demo that doesn't work with IE10. I downloaded the code and used it with jQuery and it seems to work fine with IE10 (plus other browsers). Appears to be only how the event handler is used.

**Comment by mintchaos** [comment]
Yeah, the example page uses native custom event stuff which has mostly be superseded by the back.close() method. I should change the example page to match.

**Comment by EricLayne** [comment]
Oh great.  I'll download and check it out then.  Thanks!
